### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by zhaishengfu** [vritvij/Project-Ignite#2]
Hello， I download the project but cant open it using 4.15

**Comment by vritvij** [comment]
Fixing it now

**Comment by zhaishengfu** [comment]
When can you finish it? I Wonder Why all of your assets is not recognized by my unreal 4.15

**Comment by vritvij** [comment]
I got the assets working as of now in 4.15. But there is some problem in the notifies in my montages. It leads to a crash if either the player or the enemy dies. I'll be done as soon as I fix that.

**Comment by zhaishengfu** [comment]
Thank you. I am eager to see your projects.

**Comment by vritvij** [comment]
I've updated the project to UE4.15 and everything works as of now. Just make sure to enable EQS (Environmental Query System) in Editor Settings, otherwise the AI will not work.

**Comment by zhaishengfu** [comment]
Thank you very much!!
